version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: juzessa/kittygram_final_backend
    env_file: .env
    volumes:
    - static:/backend_static
    - media:/media
    depends_on:
    - db
  frontend:
    env_file: .env
    image: juzessa/kittygram_final_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: juzessa/kittygram_final_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles
      - media:/media